name: Reusable Check Package

on:
  workflow_call:
    inputs:
      import-name:
        description: 'Import name to test with after installation'
        required: true
        type: string
      pypi-name:
        description: 'PyPI name to install the package with'
        required: true
        type: string

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # max-parallel: 6
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]
        python-version: [3.7, 3.9]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare env
        run: pip install -U "twine==4.0.*" setuptools wheel check-manifest

      - name: Prepare env on Windows
        if: runner.os == 'windows'
        run: |
          # this is just a hotfix because of Win cannot install it directly
          pip install -r requirements.txt --find-links https://download.pytorch.org/whl/cpu/torch_stable.html

      - name: Create package
        run: |
          python setup.py sdist bdist_wheel
          python setup.py clean

      - name: Check package
        run: |
          # Check MANIFEST.in
          check-manifest
          # Check package description
          twine check dist/*
          # Check package
          python setup.py check --metadata --strict

      - name: Install and uninstall package (archive)
        working-directory: dist
        run: |
          pip install *.tar.gz
          python -c "import ${{ inputs.import-name }}; print(${{ inputs.import-name }}.__version__)"
          pip uninstall -y ${{ inputs.pypi-name }}

      - name: Install and uninstall package (wheel)
        working-directory: dist
        run: |
          pip install *.whl
          python -c "import ${{ inputs.import-name }}; print(${{ inputs.import-name }}.__version__)"
          pip uninstall -y ${{ inputs.pypi-name }}
