name: Reusable Schema

on:
  workflow_call:
    inputs:
      azure-dir:
        description: 'Directory containing Azure Pipelines config files'
        default: './.azure-pipelines'
        required: false
        type: string

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install check-jsonschema

      - name: GitHub Workflows
        run: check-jsonschema $(find .github/workflows -name '*.yml' -a ! -name '_*.yml') --builtin-schema "github-workflows"

      - name: Azure Pipelines
        env:
          SCHEMA_FILE: https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/v1.204.0/service-schema.json
        run: check-jsonschema ${{ inputs.azure-dir }}/*.yml --schemafile "$SCHEMA_FILE"
