name: Check Package

on:
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  check:
    uses: ./.github/workflows/_check-package.yml
    with:
      import-name: pytorch_lightning
      pypi-name: pytorch-lightning
