name: Schema

on:
  push: {}
  pull_request:
    branches: [master, "release/*"]

jobs:
  check:
    uses: ./.github/workflows/_check-schema.yml
    # TODO: Update to reuse the workflow in a specific hash/branch/tag.
    # uses: PyTorchLightning/pytorch-lightning/.github/workflows/_check-schema.yml@master
